-- Fish Art Community Chat System Database Migration
-- Date: 2025-11-06
-- Purpose: Remove battle system, add community chat sessions

-- ==================================================================
-- STEP 1: Remove battle-related fields from fish table
-- ==================================================================

-- Drop battle-related columns
ALTER TABLE fish 
DROP COLUMN IF EXISTS talent,
DROP COLUMN IF EXISTS level,
DROP COLUMN IF EXISTS experience,
DROP COLUMN IF EXISTS health,
DROP COLUMN IF EXISTS max_health,
DROP COLUMN IF EXISTS battle_power,
DROP COLUMN IF EXISTS last_exp_update,
DROP COLUMN IF EXISTS is_in_battle_mode,
DROP COLUMN IF EXISTS position_row,
DROP COLUMN IF EXISTS total_wins,
DROP COLUMN IF EXISTS total_losses;

-- Drop battle-related indexes (if they exist)
DROP INDEX IF EXISTS idx_fish_battle;
DROP INDEX IF EXISTS idx_fish_battle_power;
DROP INDEX IF EXISTS idx_fish_level;

-- ==================================================================
-- STEP 2: Drop battle-related tables
-- ==================================================================

DROP TABLE IF EXISTS battle_log CASCADE;
DROP TABLE IF EXISTS battle_config CASCADE;

-- ==================================================================
-- STEP 3: Create community_chat_sessions table (批次存储对话)
-- ==================================================================

CREATE TABLE IF NOT EXISTS community_chat_sessions (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    topic VARCHAR(100) NOT NULL,
    time_of_day VARCHAR(20),
    participant_fish_ids UUID[] NOT NULL,
    dialogues JSONB NOT NULL,
    display_duration INT DEFAULT 0,
    created_at TIMESTAMP DEFAULT NOW(),
    expires_at TIMESTAMP DEFAULT NOW() + INTERVAL '7 days'
);

-- Add comments for documentation
COMMENT ON TABLE community_chat_sessions IS 'Stores batch dialogues generated by COZE AI for community chat';
COMMENT ON COLUMN community_chat_sessions.topic IS 'Chat topic, e.g., "Morning Greetings", "Swimming Fun"';
COMMENT ON COLUMN community_chat_sessions.time_of_day IS 'Time period: morning, afternoon, evening, night';
COMMENT ON COLUMN community_chat_sessions.participant_fish_ids IS 'Array of fish IDs that participated in this chat';
COMMENT ON COLUMN community_chat_sessions.dialogues IS 'Full dialogue JSON: {messages: [{fishId, fishName, message, sequence}]}';
COMMENT ON COLUMN community_chat_sessions.display_duration IS 'Total playback duration in seconds (messages × 6)';
COMMENT ON COLUMN community_chat_sessions.expires_at IS 'Auto-cleanup date (7 days from creation)';

-- Create indexes
CREATE INDEX IF NOT EXISTS idx_session_created 
ON community_chat_sessions(created_at DESC);

CREATE INDEX IF NOT EXISTS idx_session_expires 
ON community_chat_sessions(expires_at);

CREATE INDEX IF NOT EXISTS idx_session_topic 
ON community_chat_sessions(topic);

CREATE INDEX IF NOT EXISTS idx_session_time 
ON community_chat_sessions(time_of_day);

-- Create GIN index for participant_fish_ids array (for efficient querying)
CREATE INDEX IF NOT EXISTS idx_session_participants 
ON community_chat_sessions USING GIN(participant_fish_ids);

-- ==================================================================
-- STEP 4: Ensure user_subscriptions table exists (from previous migration)
-- ==================================================================

-- This should already exist from migrate-dialogue-system.sql
-- Just verify it exists
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.tables 
        WHERE table_name = 'user_subscriptions'
    ) THEN
        -- Create it if it doesn't exist
        CREATE TABLE user_subscriptions (
            user_id VARCHAR(255) PRIMARY KEY,
            plan VARCHAR(20) NOT NULL DEFAULT 'free',
            stripe_customer_id VARCHAR(255),
            stripe_subscription_id VARCHAR(255),
            current_period_start TIMESTAMP,
            current_period_end TIMESTAMP,
            is_active BOOLEAN DEFAULT FALSE,
            cancel_at_period_end BOOLEAN DEFAULT FALSE,
            created_at TIMESTAMP DEFAULT NOW(),
            updated_at TIMESTAMP DEFAULT NOW()
        );
        
        -- Add check constraint for plan
        ALTER TABLE user_subscriptions 
        ADD CONSTRAINT subscription_plan_check 
        CHECK (plan IN ('free', 'basic', 'premium'));
        
        -- Create indexes
        CREATE INDEX idx_subscription_stripe_customer 
        ON user_subscriptions(stripe_customer_id);
        
        CREATE INDEX idx_subscription_stripe_subscription 
        ON user_subscriptions(stripe_subscription_id);
        
        CREATE INDEX idx_subscription_active 
        ON user_subscriptions(is_active) WHERE is_active = TRUE;
        
        RAISE NOTICE 'Created user_subscriptions table';
    ELSE
        RAISE NOTICE 'user_subscriptions table already exists';
    END IF;
END$$;

-- ==================================================================
-- STEP 5: Add automatic cleanup function for expired sessions
-- ==================================================================

CREATE OR REPLACE FUNCTION cleanup_expired_chat_sessions()
RETURNS INTEGER AS $$
DECLARE
    deleted_count INTEGER;
BEGIN
    DELETE FROM community_chat_sessions 
    WHERE expires_at < NOW();
    
    GET DIAGNOSTICS deleted_count = ROW_COUNT;
    RETURN deleted_count;
END;
$$ LANGUAGE plpgsql;

COMMENT ON FUNCTION cleanup_expired_chat_sessions IS 
'Deletes expired chat sessions (older than 7 days). Can be called by a cron job.';

-- ==================================================================
-- STEP 6: Create view for active chats (last 24 hours)
-- ==================================================================

CREATE OR REPLACE VIEW recent_chat_sessions AS
SELECT 
    id,
    topic,
    time_of_day,
    participant_fish_ids,
    jsonb_array_length(dialogues->'messages') as message_count,
    display_duration,
    created_at
FROM community_chat_sessions
WHERE created_at > NOW() - INTERVAL '24 hours'
ORDER BY created_at DESC;

COMMENT ON VIEW recent_chat_sessions IS 
'Shows chat sessions from the last 24 hours with message counts';

-- ==================================================================
-- STEP 7: Grant permissions (adjust as needed for your Hasura setup)
-- ==================================================================

-- These are examples - adjust based on your Hasura roles
-- GRANT SELECT, INSERT ON community_chat_sessions TO authenticated;
-- GRANT SELECT ON recent_chat_sessions TO authenticated;
-- GRANT EXECUTE ON FUNCTION cleanup_expired_chat_sessions TO authenticated;

-- ==================================================================
-- MIGRATION COMPLETE - Display Summary
-- ==================================================================

DO $$
DECLARE
    fish_count INT;
    fish_with_names INT;
    subscription_count INT;
    session_count INT;
    battle_log_exists BOOLEAN;
    battle_config_exists BOOLEAN;
BEGIN
    -- Check what exists
    SELECT COUNT(*) INTO fish_count FROM fish;
    SELECT COUNT(*) INTO fish_with_names FROM fish WHERE fish_name IS NOT NULL;
    SELECT COUNT(*) INTO subscription_count FROM user_subscriptions;
    SELECT COUNT(*) INTO session_count FROM community_chat_sessions;
    
    SELECT EXISTS (
        SELECT 1 FROM information_schema.tables WHERE table_name = 'battle_log'
    ) INTO battle_log_exists;
    
    SELECT EXISTS (
        SELECT 1 FROM information_schema.tables WHERE table_name = 'battle_config'
    ) INTO battle_config_exists;
    
    RAISE NOTICE '==========================================================';
    RAISE NOTICE 'Community Chat System Migration Completed Successfully!';
    RAISE NOTICE '==========================================================';
    RAISE NOTICE '';
    RAISE NOTICE 'Database Changes:';
    RAISE NOTICE '  ✅ Removed battle fields from fish table';
    RAISE NOTICE '  ✅ Dropped battle_log table: %', NOT battle_log_exists;
    RAISE NOTICE '  ✅ Dropped battle_config table: %', NOT battle_config_exists;
    RAISE NOTICE '  ✅ Created community_chat_sessions table';
    RAISE NOTICE '  ✅ Created cleanup function';
    RAISE NOTICE '  ✅ Created recent_chat_sessions view';
    RAISE NOTICE '';
    RAISE NOTICE 'Current Data:';
    RAISE NOTICE '  📊 Total fish: %', fish_count;
    RAISE NOTICE '  🐟 Fish with names: %', fish_with_names;
    RAISE NOTICE '  👥 User subscriptions: %', subscription_count;
    RAISE NOTICE '  💬 Chat sessions: %', session_count;
    RAISE NOTICE '';
    RAISE NOTICE 'Next Steps:';
    RAISE NOTICE '  1. Track new tables in Hasura console:';
    RAISE NOTICE '     - community_chat_sessions';
    RAISE NOTICE '     - recent_chat_sessions (view)';
    RAISE NOTICE '  2. Configure table permissions in Hasura';
    RAISE NOTICE '  3. Untrack old battle tables (if still tracked)';
    RAISE NOTICE '  4. Set up cron job to call cleanup_expired_chat_sessions()';
    RAISE NOTICE '  5. Update GraphQL schema';
    RAISE NOTICE '';
    RAISE NOTICE '==========================================================';
    RAISE NOTICE 'Schema Ready for Phase 2: COZE AI Integration';
    RAISE NOTICE '==========================================================';
END$$;

